"""approval batches

Revision ID: 102113bd290d
Revises: 6d06997bb93e
Create Date: 2026-09-20 00:07:28.868548

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "102113bd290d"
down_revision: str | Sequence[str] | None = "6d06997bb93e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "approvals",
        sa.Column("tool_calls_json", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.drop_column("approvals", "arguments_json")
    op.drop_column("approvals", "tool_name")
    op.drop_column("approvals", "risk_level")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "approvals",
        sa.Column("risk_level", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    )
    op.add_column(
        "approvals",
        sa.Column("tool_name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    )
    op.add_column(
        "approvals",
        sa.Column(
            "arguments_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("approvals", "tool_calls_json")
    # ### end Alembic commands ###
