"""task observability fields

Revision ID: 436c2742e272
Revises: a726acfc8f34
Create Date: 2026-09-20 22:06:30.505289

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "436c2742e272"
down_revision: str | Sequence[str] | None = "a726acfc8f34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("memory_hits", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("tasks", sa.Column("skill_selected", sa.String(length=64), nullable=True))
    op.add_column(
        "tasks",
        sa.Column("tools_available_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "tasks",
        sa.Column("tools_discovered_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "tasks", sa.Column("agent_handoffs", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "agent_handoffs")
    op.drop_column("tasks", "tools_discovered_count")
    op.drop_column("tasks", "tools_available_count")
    op.drop_column("tasks", "skill_selected")
    op.drop_column("tasks", "memory_hits")
    # ### end Alembic commands ###
