"""multi agent workflows

Revision ID: 7d5394f1c60c
Revises: 436c2742e272
Create Date: 2026-09-20 22:23:26.141109

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d5394f1c60c"
down_revision: str | Sequence[str] | None = "436c2742e272"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("context_strategy", sa.String(length=32), nullable=False),
        sa.Column("complexity", sa.String(length=16), nullable=False),
        sa.Column("workspace_root", sa.String(length=512), nullable=False),
        sa.Column("phases_json", sa.JSON(), nullable=False),
        sa.Column("final_verdict", sa.String(length=32), nullable=True),
        sa.Column("files_changed", sa.JSON(), nullable=False),
        sa.Column("tests_passed", sa.Integer(), nullable=True),
        sa.Column("tests_failed", sa.Integer(), nullable=True),
        sa.Column("agent_handoffs", sa.Integer(), nullable=False),
        sa.Column("total_input_tokens", sa.Integer(), nullable=False),
        sa.Column("total_output_tokens", sa.Integer(), nullable=False),
        sa.Column("developer_conversation_state", sa.JSON(), nullable=False),
        sa.Column("developer_events_json", sa.JSON(), nullable=False),
        sa.Column("pending_approval_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflows")
    # ### end Alembic commands ###
