"""workflow memory hits

Revision ID: a4e63f9ebd78
Revises: 7d5394f1c60c
Create Date: 2026-09-20 22:47:23.783455

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4e63f9ebd78"
down_revision: str | Sequence[str] | None = "7d5394f1c60c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflows", sa.Column("memory_hits", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "memory_hits")
    # ### end Alembic commands ###
